apiVersion: v1
kind: Pod
metadata:
  name: myapp-container
  labels:
   name: myapp-container
spec:
  containers:
  - name: myapp-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo the app is running && sleep 3600']
    env:
    - name: FIRSTNAME
      value: "Yash"
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c']
    args: ['until nslookup myservice.default.svc.cluster.local; do echo waiting for service to br up;']